# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# ignore all warnings from all pods
inhibit_all_warnings!

target 'AATA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for AATA
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'R.swift'
  pod 'IQKeyboardManagerSwift'
  pod 'Toast-Swift'
  pod 'Cartography'
  pod 'SideMenu'
  pod 'DropDown'
  pod 'SideMenuSwift'
  pod 'PINCache'
  # Add the pod for AWS.
  #  pod 'AmazonFreeRTOS'
  # pod 'AmazonFreeRTOS', :git =>'https://github.com/mwillbanks/amazon-freertos-ble-ios-sdk.git', :branch => 'fix/xcode13-swift55-support'
  pod 'AWSMobileClient'
  pod 'AWSIoT'
  # 3. Frameworks to be imported
  # pod 'lottie-ios'
  pod 'Charts'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '7.12.0'

end
